-- TABLE FOR DEPARTMENTS
DROP TABLE EMPL;
DROP TABLE DEPT;

CREATE TABLE DEPT(DEPT_ID NUMBER(2) CONSTRAINT PK_DEPT_ID PRIMARY KEY,
                  DEPT_NAME VARCHAR2(20) CONSTRAINT NN_DEPT_NAME NOT NULL,
                  NB_EMP NUMBER(3) CONSTRAINT CK_NB_EMP CHECK(NB_EMP>5));

-- TABLE FOR EMPLOYEES
CREATE TABLE EMPL(EMP_ID NUMBER(4) CONSTRAINT PK_EMP_ID PRIMARY KEY,
                  EMP_NAME VARCHAR2(30) NOT NULL,
                  EMP_TYPE VARCHAR2(10) DEFAULT 'TEMP',
                  EMP_HDATE DATE,
                  EMP_EMAIL VARCHAR2(30) CONSTRAINT UK_EMP_EMAIL UNIQUE,
                  EMP_AGE NUMBER(3) CONSTRAINT CK_EMP_AGE CHECK(EMP_AGE>16),
                  EMP_DEP NUMBER(2) CONSTRAINT FK_EMP_DEP
                                    REFERENCES DEPT(DEPT_ID));

