-- QUESTION 1
SELECT LAST_NAME, FIRST_NAME, HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE < TO_DATE('APR-01-1988', 'MON-DD-YYYY');

-- QUESTION 2
SELECT LAST_NAME, FIRST_NAME, SALARY, SALARY - (SALARY * 0.14) AS REDUCED_SALARY
FROM EMPLOYEE
WHERE JOB_ID IN (667, 668);

-- QUESTION 3
SELECT E.LAST_NAME, D.NAME AS DEPARTMENT_NAME, J.FUNCTION AS JOB_TITLE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN JOB J ON E.JOB_ID = J.JOB_ID
ORDER BY J.FUNCTION DESC;

-- QUESTION 4
SELECT LAST_NAME, FIRST_NAME
FROM EMPLOYEE
WHERE LAST_NAME LIKE '%T%_%T%';

-- QUESTION 5
SELECT D.NAME, COUNT(*) AS TOTAL_NUMBER_OF_EMPLOYEES
FROM DEPARTMENT D
JOIN EMPLOYEE E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.NAME;

-- QUESTION 6
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) = (SELECT MIN(COUNT(DEPARTMENT_ID)) FROM EMPLOYEE GROUP BY DEPARTMENT_ID)
OR COUNT(*) = (SELECT MAX(COUNT(DEPARTMENT_ID)) FROM EMPLOYEE GROUP BY DEPARTMENT_ID);

-- QUESTION 7
UPDATE EMPLOYEE SET SALARY = SALARY * 1.12 WHERE DEPARTMENT_ID = 10;
UPDATE EMPLOYEE SET SALARY = SALARY * 1.10 WHERE DEPARTMENT_ID = 12;
UPDATE EMPLOYEE SET SALARY = SALARY * 1.05 WHERE DEPARTMENT_ID NOT IN (10, 12);

-- QUESTION 8
SELECT E.LAST_NAME AS EMPLOYEE_LAST_NAME, E.SALARY AS EMPLOYEE_SALARY, M.LAST_NAME AS MANAGER_LAST_NAME, M.SALARY AS MANAGER_SALARY
FROM EMPLOYEE E
JOIN EMPLOYEE M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.HIRE_DATE < M.HIRE_DATE;

-- QUESTION 9
-- A
CREATE OR REPLACE VIEW V_AVGSALARYDEP AS
SELECT E.DEPARTMENT_ID, D.NAME, ROUND(AVG(SALARY), 2) AS AVG_DEPARTMENT_SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY E.DEPARTMENT_ID, D.NAME;

-- B
SELECT * FROM V_AVGSALARYDEP;

-- QUESTION 10
SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY =
(SELECT MAX(SALARY)
FROM EMPLOYEE 
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE));



