-- QUESTION 2
-- this was the script that was run to create the user "booking"
CONNECT system/pwd
alter session set "_ORACLE_SCRIPT"=true; 
DROP USER booking cascade;
CREATE USER booking IDENTIFIED BY booking 
DEFAULT TABLESPACE USERS;

-- QUESTION 3
GRANT CONNECT,RESOURCE TO booking ;
GRANT UNLIMITED TABLESPACE TO booking;
grant create view to booking ;

-- QUESTION 4
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;

CREATE TABLE CLIENT(
CLIENT_ID NUMBER(3) CONSTRAINT PK_C_CLIENT_ID PRIMARY KEY,
C_NAME VARCHAR(20) CONSTRAINT NN_C_NAME NOT NULL,
C_PHONE VARCHAR(20),
C_ADDRESS VARCHAR(60),
C_REGION VARCHAR(20) DEFAULT 'MONTREAL'
);

CREATE TABLE HOTEL(
HOTEL_ID NUMBER(4) CONSTRAINT PK_H_HOTEL_ID PRIMARY KEY,
HOTEL_NAME VARCHAR(30) CONSTRAINT NN_HOTEL_NAME NOT NULL,
HOTEL_GRADE NUMBER(1) CONSTRAINT CK_HOTEL_GRADE CHECK(HOTEL_GRADE IN (1,2,3,4)),
HOTEL_PHONE VARCHAR(20)
);

CREATE TABLE BOOKING(
CLIENT_ID NUMBER(3) CONSTRAINT FK_B_CLIENT_ID REFERENCES CLIENT(CLIENT_ID),
HOTEL_ID NUMBER(4) CONSTRAINT FK_B_HOTEL_ID REFERENCES HOTEL(HOTEL_ID),
BOOKING_DATE DATE,
CONSTRAINT PK_BOOKING PRIMARY KEY(CLIENT_ID, BOOKING_DATE)
);

-- QUESTION 5
ALTER TABLE BOOKING ADD(
DURATION NUMBER(2) CONSTRAINT CK_DURATION CHECK(DURATION>0),
CONSTRAINT CK_BOOKING_DATE CHECK(BOOKING_DATE IS NOT NULL)
);

-- QUESTION 6
ALTER TABLE CLIENT RENAME COLUMN C_PHONE TO CLIENT_PHONE;
ALTER TABLE CLIENT RENAME COLUMN C_REGION TO CLIENT_REGION;
ALTER TABLE CLIENT RENAME COLUMN C_ADDRESS TO CLIENT_ADDRESS;
ALTER TABLE CLIENT ADD CLIENT_LNAME VARCHAR(20) CONSTRAINT NN_CLIENT_LNAME NOT NULL;

-- QUESTION 7
ALTER TABLE BOOKING MODIFY CLIENT_ID NUMBER(5);
ALTER TABLE CLIENT MODIFY CLIENT_ID NUMBER(5);

-- QUESTION 8
ALTER TABLE HOTEL ADD PAYMENT NUMBER(3,2) CONSTRAINT CK_PAYMENT CHECK(PAYMENT<999.99);
ALTER TABLE HOTEL DROP CONSTRAINT CK_HOTEL_GRADE;
ALTER TABLE HOTEL ADD CONSTRAINT CK_HOTEL_GRADE CHECK(HOTEL_GRADE IN (1,2,3));

-- QUESTION 9
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='BOOKING';

-- QUESTION 10
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME='HOTEL';
SELECT STATUS FROM USER_CONSTRAINTS WHERE TABLE_NAME='HOTEL';
SELECT TABLE_NAME,STATUS FROM USER_TABLES WHERE TABLE_NAME='CLIENT';
SELECT STATUS FROM USER_CONSTRAINTS WHERE TABLE_NAME='CLIENT';
