DROP TABLE JOB;
DROP TABLE EMPLOYEE;
DROP TABLE HISTORY_JOB;

CREATE TABLE JOB(JOB_ID NUMBER(2) CONSTRAINT JOB_PK PRIMARY KEY,
                 JOB_TITLE VARCHAR(30) CONSTRAINT JOB_TITLE_NN NOT NULL);
                 
CREATE TABLE EMPLOYEE(EMP_ID NUMBER(4) CONSTRAINT EMPLOYEE_PK PRIMARY KEY,
                      NAME VARCHAR(30) CONSTRAINT NAME_NN NOT NULL,
                      B_DATE DATE,
                      H_DATE DATE,
                      JOB_ID NUMBER(2) CONSTRAINT JOB_ID_FK
                                       REFERENCES JOB(JOB_ID),
                      CONSTRAINT DATE_CK CHECK(H_DATE>B_DATE));
                      
CREATE TABLE HISTORY_JOBS(EMP_ID NUMBER(4) CONSTRAINT HISTORY_JOBS_FK2
                                           REFERENCES EMPLOYEE(EMP_ID),
                          JOB_ID NUMBER(2) CONSTRAINT JOB_ID_FK1
                                           REFERENCES JOB(JOB_ID),
                          START_DATE DATE,
                          END_DATE DATE,
                          CONSTRAINT HISTORY_JOBS_PK PRIMARY KEY(EMP_ID, JOB_ID, START_DATE),
                          CONSTRAINT START_END_DATE CHECK (START_DATE<END_DATE));
                          
-- QUERY THE ORABLE DICTIONARY
SELECT TABLE_NAME, CREATED FROM USER_TABLES;
SELECT OBJECT_NAME, CREATED FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE';

-- CHANGE THE SESSION SETTINGS
ALTER SESSION SET NLS_DATE_FORMAT='DD-MONTH-YYYY';

-- DISPLAY CONSTRAINTS AND COLUMNS 
SELECT CONSTRAINT_NAME,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='HISTORY_JOBS';

SELECT CONSTRAINT_NAME, TABLE_NAME, SEARCH_CONDITION FROM USER_CONSTRAINTS 
WHERE TABLE_NAME='HISTORY_JOBS'
AND CONSTRAINT_NAME='START_END_DATE';

SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='HISTORY_JOBS';

-- USER_TABLES : INFORMATION ABOUT THE TABLES
-- USER_OBJECTS : INFORMATION ABOUT TABLES, VIEW, INDEXES (OBJECTS)
-- USER_CONSTRAINTS : INFORMATION ABOUT TABLES AND THEIR CONSTRAINTS
-- USER_CONS_COLUMNS : INFORMATION ABOUT TABLES, COLUMNS AND THEIR CONSTRAINTS

SELECT OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE='TABLE';

-- HOW TO DESCRIBE A TABLE
DESC HISTORY_JOBS;

DESC USER_OBJECTS;

SELECT OBJECT_NAME, OBJECT_TYPE, LAST_DDL_TIME
FROM USER_OBJECTS;