-- Exercise 01

-- 1
SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER;
--2
SELECT LAST_NAME ||' '||BIRTH_DATE
FROM DRIVER;
--3
SELECT LAST_NAME, SALARY*1.05 NEW_SALARY
FROM DRIVER;

SELECT LAST_NAME, SALARY*1.05 "NEW SALARY"
FROM DRIVER;

--4
SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE SALARY>55000;
--5 
SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE DRIVER_ID IN ('P300','P500','P1000');
--6
SELECT CONSTRUCTOR_ID,NAME
FROM CONSTRUCTOR
WHERE NAME LIKE 'M%';

--7

SELECT DRIVER_ID,COMP_DATE FROM COMPETITION
WHERE NB_OF_ROUNDS <60;

SELECT DRIVER_ID,COMP_DATE FROM COMPETITION
WHERE NB_OF_ROUNDS <60
AND   QUIT_COMP='Y';

--8

SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE LAST_NAME NOT LIKE 'S%';


--9

SELECT LAST_NAME,FIRST_NAME,SALARY,HIRE_DATE
FROM DRIVER
WHERE HIRE_DATE <= TO_DATE('01-JAN-2000','DD-MON-YYYY');


--10

SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE LAST_NAME LIKE '%A%' OR LAST_NAME LIKE '%E%';

-- CONTAIN A AND E
SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE LAST_NAME LIKE '%A%' AND LAST_NAME LIKE '%E%';
-- CONTAIN A FOLLOWED BY E
SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE LAST_NAME LIKE '%A%E%'; 
--11

SELECT DISTINCT CONSTRUCTOR_ID FROM COMPETITION;

--12

SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE SALARY BETWEEN 55000 AND 65000
ORDER BY SALARY ASC;

SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE SALARY BETWEEN 55000 AND 65000
ORDER BY SALARY ;

SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE SALARY >= 55000 AND SALARY<=65000
ORDER BY SALARY ;

--13

SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE LAST_NAME LIKE '_A%';

--14

SELECT NAME FROM CONSTRUCTOR
WHERE NAME LIKE '%O_%O%';

--15
SELECT LAST_NAME,FIRST_NAME,SALARY
FROM DRIVER
WHERE FIRST_NAME LIKE '%A'
OR FIRST_NAME LIKE '%E'
OR FIRST_NAME LIKE '%I'
OR FIRST_NAME LIKE '%O'
OR FIRST_NAME LIKE '%U'
OR FIRST_NAME LIKE '%Y';

--16

SELECT DRIVER_ID
FROM COMPETITION
WHERE NB_OF_ROUNDS IS NULL;


-- Exercise 02

--1 
SELECT COUNT(*) FROM COMPETITION;

--2
SELECT COUNT(*) FROM COMPETITION
WHERE DURATION IS NOT NULL;

OR

SELECT COUNT(DURATION) FROM COMPETITION;

--3

SELECT SUM(SALARY),AVG(SALARY),MIN(SALARY),MAX(SALARY)
FROM DRIVER;

--4

SELECT COUNT(*) FROM COMPETITION
WHERE QUIT_COMP='Y';

--5

SELECT COUNT(*) FROM DRIVER
WHERE TO_CHAR(HIRE_DATE,'YYYY') ='1995';

OU

SELECT COUNT(*) FROM DRIVER
WHERE HIRE_DATE BETWEEN '01-JAN-95' AND '01-JAN-96'
AND HIRE_DATE <> '01-JAN-96'

or

SELECT COUNT(*) FROM DRIVER
WHERE EXTRACT( YEAR FROM HIRE_DATE)=1995;

--6
SELECT COUNTRY_ID,SUM(SALARY)
FROM DRIVER
GROUP BY COUNTRY_ID;


--7 

SELECT COUNT(*) FROM COMPETITION
WHERE NB_OF_ROUND>=67;


--8

SELECT COUNTRY_NAME
FROM DRIVER
HAVING COUNT(*)>=2
GROUP BY COUNTRY_NAME;

-- Exercise 03
--1
SELECT CIRCUIT_ID,DESCRIPTION,ROUND_LENGTH,NAME
FROM CIRCUIT
JOIN COUNTRY USING(COUNTRY_ID);

2--
SELECT DRIVER_ID,LAST_NAME,DURATION 
FROM   DRIVER
JOIN COMPETITION USING(DRIVER_ID)
WHERE   QUIT_COMP='N'
ORDER BY DURATION DESC;

3--

SELECT DRIVER_ID,LAST_NAME,FIRST_NAME
FROM DRIVER 
JOIN COMPETITION USING (DRIVER_ID)
WHERE DURATION<1.5370
AND  QUIT_COMP='N';

--4 

SELECT LAST_NAME,FIRST_NAME,COUNTRY_NAME,C2.NAME,C3.NB_OF_ROUNDS
FROM COMPETITION C3
JOIN DRIVER D ON D.DRIVER_ID=C3.DRIVER_ID
JOIN CONSTRUCTOR C2 ON C2.CONSTRUCTOR_ID=C3.CONSTRUCTOR_ID;

--5 

SELECT LAST_NAME,C1.NAME CONSTRUCTEUR,DESCRIPTION,C2.NAME COUNTRY,C3.NB_OF_ROUNDS NB_ROUNDS
FROM COMPETITION C3
JOIN DRIVER D ON D.DRIVER_ID=C3.DRIVER_ID
JOIN CONSTRUCTOR C1 ON C1.CONSTRUCTOR_id=C3.CONSTRUCTOR_ID
JOIN CIRCUIT C4  ON C4.CIRCUIT_ID=C3.CIRCUIT_ID
JOIN COUNTRY C2  ON C4.COUNTRY_ID=C2.COUNTRY_ID;

--6
CREATE OR REPLACE VIEW V1_COMPETITION
AS
SELECT LAST_NAME,C1.NAME CONSTRUCTEUR,DESCRIPTION,C2.NAME COUNTRY,C3.NB_OF_ROUNDS NB_ROUNDS
FROM COMPETITION C3
JOIN DRIVER D ON D.DRIVER_ID=C3.DRIVER_ID
JOIN CONSTRUCTOR C1 ON C1.CONSTRUCTOR_id=C3.CONSTRUCTOR_ID
JOIN CIRCUIT C4  ON C4.CIRCUIT_ID=C3.CIRCUIT_ID
JOIN COUNTRY C2  ON C4.COUNTRY_ID=C2.COUNTRY_ID;

--7

CREATE OR REPLACE VIEW V2_COMPETITION (DRIVER_LNAME,CONST_NAME,DISTANCE,SPEED)
AS
SELECT LAST_NAME,NAME, DISTANCE, SPEED
FROM COMPETITION
JOIN DRIVER USING(DRIVER_ID)
JOIN CONSTRUCTOR USING (CONSTRUCTOR_ID);

--8
SELECT NAME,COUNT(*)
FROM COMPETITION 
JOIN CONSTRUCTOR USING(CONSTRUCTOR_ID)
GROUP BY NAME
HAVING COUNT(*)>=2;


-- Exercise 04

-- 1

SELECT CIRCUIT_ID,DESCRIPTION,ROUND_LENGTH,NAME
FROM CIRCUIT C1, COUNTRY C2
WHERE C1.COUNTRY_ID=C2.COUNTRY_ID;

--2

SELECT D.DRIVER_ID,LAST_NAME,DURATION 
FROM   DRIVER D, COMPETITION C
WHERE D.DRIVER_ID=C.DRIVER_ID
AND   QUIT_COMP='N'
ORDER BY DURATION DESC;

--3
SELECT D.DRIVER_ID,LAST_NAME,FIRST_NAME
FROM DRIVER D, COMPETITION C
WHERE D.DRIVER_ID=C.DRIVER_ID
AND  DURATION<1.5370
AND  QUIT_COMP='N';

--4 
SELECT LAST_NAME,FIRST_NAME,C1.NAME,C2.NAME,C3.NB_OF_ROUNDS
FROM DRIVER D,COUNTRY C1,CONSTRUCTOR C2,COMPETITION C3
WHERE D.DRIVER_ID=C3.DRIVER_ID
AND   C2.CONSTRUCTOR_ID=C3.CONSTRUCTOR_ID
AND   D.COUNTRY_ID=C1.COUNTRY_ID;

--OU

SELECT LAST_NAME,FIRST_NAME,COUNTRY_NAME,C2.NAME,C3.NB_OF_ROUNDS
FROM DRIVER D,CONSTRUCTOR C2,COMPETITION C3
WHERE D.DRIVER_ID=C3.DRIVER_ID
AND   C2.CONSTRUCTOR_ID=C3.CONSTRUCTOR_ID;


--5


SELECT LAST_NAME,C1.NAME CONSTRUCTEUR,DESCRIPTION,C2.NAME PAYS,C3.NB_OF_ROUNDS
FROM   DRIVER D, CONSTRUCTOR C1, COUNTRY C2, COMPETITION C3, CIRCUIT C4
WHERE D.DRIVER_ID=C3.DRIVER_ID
AND   C1.CONSTRUCTOR_id=c3.CONSTRUCTOR_ID
AND   C4.CIRCUIT_ID=C3.CIRCUIT_ID
AND   C4.COUNTRY_ID=C2.COUNTRY_ID;

--6
CREATE OR REPLACE VIEW V1_COMPETITION
AS
SELECT LAST_NAME,C1.NAME CONSTRUCTEUR,DESCRIPTION,C2.NAME PAYS,C3.NB_OF_ROUNDS
FROM   DRIVER D, CONSTRUCTOR C1, COUNTRY C2, COMPETITION C3, CIRCUIT C4
WHERE D.DRIVER_ID=C3.DRIVER_ID
AND   C1.CONSTRUCTOR_id=c3.CONSTRUCTOR_ID
AND   C4.CIRCUIT_ID=C3.CIRCUIT_ID
AND   C4.COUNTRY_ID=C2.COUNTRY_ID;

--7
CREATE OR REPLACE VIEW V2_COMPETITION (NOM_ATHLETE,NOM_CONSTRUCTEUR,DISTANCE,VITESSE)
AS
SELECT LAST_NAME,C1.NAME CONSTRUCTEUR, DISTANCE, SPEED
FROM   DRIVER D, CONSTRUCTOR C1,COMPETITION C2
WHERE  D.DRIVER_ID=C2.DRIVER_ID
AND    C1.CONSTRUCTOR_ID=C2.CONSTRUCTOR_ID;

-- 8
 
SELECT NAME,COUNT(*)
FROM CONSTRUCTOR C1,COMPETITION C2
WHERE C1.CONSTRUCTOR_ID=C2.CONSTRUCTOR_ID
HAVING COUNT(*)>=2
GROUP BY NAME;


-- Exercise 05

Solve DML Questions 
10.c
ALTER TABLE COMPETITION
ADD DISTANCE NUMBER(5,2);

UPDATE COMPETITION C1
SET DISTANCE = NB_OF_ROUNDS*(SELECT ROUND_LENGTH
                              FROM CIRCUIT C2
                              WHERE C1.CIRCUIT_ID=C2.CIRCUIT_ID);
11.c

ALTER TABLE COMPETITION
ADD SPEED NUMBER(5,2);

UPDATE COMPETITION
SET SPEED=DISTANCE/DURATION;

-- Exercise 06

-- Q9

SELECT LAST_NAME,FIRST_NAME,DURATION
FROM  DRIVER D ,COMPETITION C
WHERE D.DRIVER_ID=C.DRIVER_ID
AND QUIT_COMP='N'
AND DURATION <= (SELECT AVG(DURATION) 
                 FROM COMPETITION );

-- OR 
SELECT LAST_NAME,FIRST_NAME,DURATION
FROM DRIVER 
JOIN COMPETITION USING (DRIVER_ID)
WHERE QUIT_COMP='N'
AND DURATION <= (SELECT AVG(DURATION) 
                 FROM COMPETITION );
                 

--Q10

SELECT LAST_NAME,SALARY
FROM  DRIVER
WHERE SALARY >= (SELECT SALARY
                                  FROM DRIVER
                                  WHERE UPPER(LAST_NAME)=UPPER('Montoya'));

--Q11

SELECT LAST_NAME,SALARY
FROM DRIVER
WHERE SALARY = (SELECT MAX(SALARY) FROM DRIVER);
-- OR 
SELECT LAST_NAME,SALARY
FROM DRIVER
WHERE SALARY >=ALL (SELECT SALARY FROM DRIVER);


>= MAX(..) <=> >=ALL
<= MIN(..) <=> <=ALL

=  ANY    <=> IN
<> ALL    <=> NOT IN

--Q12

SELECT LAST_NAME,NB_OF_ROUNDS
FROM  DRIVER D , COMPETITION C
WHERE D.DRIVER_ID=C.DRIVER_ID
AND NB_OF_ROUNDS = (SELECT NB_OF_ROUNDS FROM COMPETITION
                                       WHERE DURATION = (SELECT MIN(DURATION)
                                                                              FROM COMPETITION
                                                                               WHERE QUIT_COMP='N'));

OR 
SELECT LAST_NAME,NB_OF_ROUNDS
FROM  DRIVER
JOIN    COMPETITION USING(DRIVER_ID)
WHERE NB_OF_ROUNDS = (SELECT NB_OF_ROUNDS FROM COMPETITION
                                       WHERE DURATION = (SELECT MIN(DURATION)
                                                                              FROM COMPETITION
                                                                               WHERE QUIT_COMP='N'));

--Q13
SELECT C1.CONSTRUCTOR_ID,NAME,COUNT(*)
FROM CONSTRUCTOR C1,COMPETITION C2
WHERE C1.CONSTRUCTOR_ID=C2.CONSTRUCTOR_ID
HAVING COUNT(*) >=ALL (SELECT COUNT(*) 
                                    FROM COMPETITION
                                    GROUP BY CONSTRUCTOR_ID)
GROUP BY C1.CONSTRUCTOR_ID,NAME;

--OR

SELECT CONSTRUCTOR_ID,NAME,COUNT(*)
FROM CONSTRUCTOR
JOIN  COMPETITION USING (CONSTRUCTOR_ID)
HAVING COUNT(*) =  (SELECT MAX(COUNT(*)) 
                                      FROM COMPETITION
                                      GROUP BY CONSTRUCTOR_ID)
GROUP BY CONSTRUCTOR_ID,NAME;


--Q14
SELECT LAST_NAME,FIRST_NAME,SPEED
FROM  DRIVER D,COMPETITION  C
WHERE D.DRIVER_ID=C.DRIVER_ID
AND SPEED BETWEEN (SELECT MIN(SPEED) FROM COMPETITION
                   WHERE DRIVER_ID IN ('P900','P500'))
           AND (SELECT MAX(SPEED) FROM COMPETITION
                   WHERE DRIVER_ID IN ('P900','P500'));

-- Q15
SELECT LAST_NAME,FIRST_NAME,DURATION
FROM  DRIVER D ,COMPETITION C
WHERE D.DRIVER_ID=C.DRIVER_ID
AND QUIT_COMP='N'
AND DURATION <= (SELECT AVG(DURATION) 
                                   FROM COMPETITION
                                   WHERE QUIT_COMP='N');
				   
                                                
--Q16:

SELECT DESCRIPTION, NB_OF_ROUNDS 
FROM CIRCUIT 
WHERE nb_of_rounds = (SELECT MAX(NB_OF_ROUNDS)
                                        FROM CIRCUIT);

Q17
SELECT LAST_NAME,SALARY
FROM    DRIVER
WHERE SALARY BETWEEN
(SELECT MIN(SALARY) FROM DRIVER 
  WHERE UPPER(LAST_NAME) = UPPER('Schumacher'))
AND
(SELECT MAX(SALARY) FROM DRIVER
WHERE UPPER(LAST_NAME) = UPPER('Schumacher'));

---------------------------
-- EXERCISE 07

--Q18 :


SELECT LAST_NAME,SALARY
FROM DRIVER
WHERE SALARY = (SELECT MIN(SALARY) FROM DRIVER)

SELECT LAST_NAME,SALARY
FROM DRIVER
WHERE SALARY >=ALL (SELECT SALARY FROM DRIVER);

--Q19 :

SELECT DESCRIPTION, NB_OF_ROUNDS 
FROM CIRCUIT 
WHERE nb_of_rounds >= ALL (SELECT NB_OF_ROUNDS
                            FROM CIRCUIT);                                       

Q20

SELECT LAST_NAME,FIRST_NAME,DURATION
FROM DRIVER D, COMPETITION C
WHERE D.DRIVER_ID=C.DRIVER_ID(+);

SELECT LAST_NAME,FIRST_NAME,DURATION
FROM DRIVER D
LEFT OUTER JOIN COMPETITION C
ON D.DRIVER_ID=C.DRIVER_ID;

				   
Q21

SELECT NAME,NVL(LAST_NAME,'NO DRIVER')
FROM COUNTRY
LEFT JOIN DRIVER USING(COUNTRY_ID)
order by name;

Q22)

SELECT count(*)
FROM COUNTRY
WHERE COUNTRY_ID NOT IN (SELECT COUNTRY_ID FROM DRIVER);

Q23)

select driver_id,last_name
from driver
where extract (year from birth_date)=1980;


select driver_id,last_name
from driver
where to_char(birth_date,'yyyy')='1980';				 
				 
				 
-- Exercise 08

Equivalent queries

Trouvez des requêtes équivalentes aux requêtes suivantes


1)   SELECT DRIVER_ID,CONSTRUCTOR_ID,DURATION
     FROM COMPETITION 
     WHERE CONSTRUCTOR_ID=20 OR CONSTRUCTOR_ID=30 OR  
     CONSTRUCTOR_ID=60
<==>

    SELECT DRIVER_ID,CONSTRUCTOR_ID,DURATION
    FROM COMPETITION 
    WHERE CONSTRUCTOR_ID in (20,30,60)



2)  SELECT DRIVER_ID,LAST_NAME,SALARY
    FROM DRIVER
    WHERE SALARY<70000 AND SALARY >57000

<==>
      SELECT DRIVER_ID,LAST_NAME,SALARY
      FROM DRIVER
      WHERE SALARY BETWEEN 57000 AND 70000
      AND SALARY NOT IN (57000,70000);



3)    SELECT DRIVER_ID FROM DRIVER 
      WHERE DRIVER_ID NOT IN 
      (SELECT DRIVER_ID FROM COMPETITION);

<==>
      SELECT DRIVER_ID FROM DRIVER 
      WHERE DRIVER_ID <> ALL (SELECT DRIVER_ID FROM COMPETITION);


4) SELECT LAST_NAME,SALARY
FROM DRIVER
WHERE SALARY >=ALL(SELECT SALARY FROM DRIVER);
<==>
SELECT LAST_NAME,SALARY
FROM DRIVER
WHERE SALARY= (SELECT MAX(SALARY) FROM DRIVER);				 

