-- QUESTION 1
SELECT C.CIRCUIT_ID, C.ROUND_LENGTH, C.DESCRIPTION, CC.NAME
FROM CIRCUIT C,COUNTRY CC
WHERE C.COUNTRY_ID = CC.COUNTRY_ID;

-- QUESTION 2
SELECT D.DRIVER_ID, D.FIRST_NAME, D.LAST_NAME 
FROM DRIVER D
JOIN COMPETITION C ON C.DRIVER_ID = D.DRIVER_ID
WHERE C.QUIT_COMP = 'N'
ORDER BY C.DURATION DESC;

-- QUESTION 3
SELECT D.DRIVER_ID, D.FIRST_NAME, D.LAST_NAME FROM DRIVER D
JOIN COMPETITION C ON C.DRIVER_ID = D.DRIVER_ID
WHERE C.QUIT_COMP = 'N' AND C.DURATION < 1.5370;

-- QUESTION 4
SELECT D.LAST_NAME, D.COUNTRY_NAME, CON.CONSTRUCTOR_NAME, COMP.NB_OF_ROUNDS 
FROM COMPETITION COMP,CONSTRUCTOR CON, DRIVER D 
WHERE CON.CONSTRUCTOR_ID = COMP.CONSTRUCTOR_ID
AND COMP.DRIVER_ID = D.DRIVER_ID;

-- QUESTION 5
SELECT D.LAST_NAME, CON.CONSTRUCTOR_NAME, CIR.DESCRIPTION, COMP.NB_OF_ROUNDS, C.NAME 
FROM COMPETITION COMP, CIRCUIT CIR, CONSTRUCTOR CON, DRIVER D, COUNTRY C
WHERE CIR.CIRCUIT_ID = COMP.CIRCUIT_ID AND
COMP.CONSTRUCTOR_ID = CON.CONSTRUCTOR_ID AND
D.DRIVER_ID = COMP.DRIVER_ID AND 
D.COUNTRY_ID = C.COUNTRY_ID;

-- QUESTION 6
