DROP TABLE COUNTRY CASCADE CONSTRAINTS;
DROP TABLE DRIVER CASCADE CONSTRAINTS;
DROP TABLE CIRCUIT CASCADE CONSTRAINTS;
DROP TABLE CONSTRUCTOR CASCADE CONSTRAINTS;
DROP TABLE COMPETITION CASCADE CONSTRAINTS;

-- COUNTRY
CREATE TABLE COUNTRY(
COUNTRY_ID NUMBER(2) CONSTRAINT COUNTRY_ID_PK PRIMARY KEY,
NAME VARCHAR(20) CONSTRAINT NAME_NN NOT NULL);

-- CREATE DRIVER TABLE
CREATE TABLE DRIVER(
DRIVER_ID VARCHAR(10) CONSTRAINT PK_DRIVER_ID PRIMARY KEY,
LAST_NAME VARCHAR(20) CONSTRAINT LAST_NAME_NN NOT NULL,
FIRST_NAME VARCHAR(20),
BIRTH_DATE DATE,
SALARY NUMBER(9),
COUNTRY_ID NUMBER(2)); 

-- CREATE CIRCUIT TABLE
CREATE TABLE CIRCUIT(
CIRCUIT_ID NUMBER(2) CONSTRAINT CIRCUIT_ID_PK PRIMARY KEY,
DESCRIPTION VARCHAR(20) CONSTRAINT DESCRIPTION_NN NOT NULL,
ROUND_LENGTH NUMBER(3),
NB_OF_ROUND NUMBER(2),
COUNTRY_ID NUMBER(2) CONSTRAINT COUNTRY_ID_FK REFERENCES COUNTRY(COUNTRY_ID));

-- CREATE CONSTRUCTOR TABLE
CREATE TABLE CONSTRUCTOR(
CONSTRUCTOR_ID NUMBER(3) CONSTRAINT CONSTRUCTOR_ID_PK PRIMARY KEY,
CONSTRUCTOR_NAME VARCHAR(20) CONSTRAINT CONSTRUCTOR_NAME_NN NOT NULL);

-- CREATE COMPETITION TABLE 
CREATE TABLE COMPETITION(
COMP_TYPE VARCHAR(1) CONSTRAINT COMP_TYPE_PK PRIMARY KEY,
DRIVER_ID VARCHAR(10) CONSTRAINT DRIVER_ID_FK REFERENCES DRIVER(DRIVER_ID),
CONSTRUCTOR_ID NUMBER(3) CONSTRAINT CONSTRUCTOR_ID_FK REFERENCES CONSTRUCTOR(CONSTRUCTOR_ID),
CIRCUIT_ID NUMBER(2) CONSTRAINT CIRCUIT_ID_FK REFERENCES CIRCUIT(CIRCUIT_ID),
COMP_DATE DATE,
DURATION NUMBER(7,6),
QUIT_COMP VARCHAR(1),
NB_OF_ROUND NUMBER(2) CONSTRAINT NB_OF_ROUND_CK CHECK(NB_OF_ROUND>0));


-- ADDING A CONSTRAINT TO COUNTRY COLUMN AND SALARY COLUMN IN /DRIVER/ TABLE
ALTER TABLE DRIVER ADD CONSTRAINT DRIVER_COUNTRY_ID_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID);
ALTER TABLE DRIVER ADD CONSTRAINT SALARY_CK CHECK(SALARY<60000);

-- MODIFYING THE COMP_TYPE CONSTRAINT IN /COMPETITION/ TABLE
ALTER TABLE COMPETITION DROP CONSTRAINT COMP_TYPE_PK;
ALTER TABLE COMPETITION ADD CONSTRAINT COMP_TYPE_CK CHECK(COMP_TYPE='P' OR COMP_TYPE='Q' OR COMP_TYPE='C');

-- ADDING CONTRAINT TO ROUND LENGTH NUMBER OF ROUNDS IN /CIRCUIT/ TABLE
ALTER TABLE CIRCUIT ADD CONSTRAINT ROUND_LENGTH CHECK(ROUND_LENGTH>0);
ALTER TABLE CIRCUIT ADD CONSTRAINT CIRCUIT_NB_OF_ROUND_CK CHECK(NB_OF_ROUND>0);

-- ADDING CONSTRAINT TO QUIT_COMP IN /COMPETITION/ TABLE
ALTER TABLE COMPETITION ADD CONSTRAINT QUIT_COMP_CK CHECK(QUIT_COMP='Y' OR QUIT_COMP='N');

-- CHANGING COLUMN DESCRIPTION SIZE TO VARCHAR(30) IN /CIRCUIT/ TABLE
ALTER TABLE CIRCUIT DROP COLUMN DESCRIPTION CASCADE CONSTRAINTS;
ALTER TABLE CIRCUIT ADD DESCRIPTION VARCHAR(30) CONSTRAINT DESCRIPTION_NN NOT NULL;    -- *** NOT GOOD ***

-- ADDING HIRE_DATE COLUMN TO /DRIVER/ TABLE
ALTER TABLE DRIVER ADD HIRE_DATE DATE;
ALTER TABLE DRIVER ADD CONSTRAINT HIRE_DATE_CK CHECK(BIRTH_DATE<HIRE_DATE);

-- MODIFY DRIVER SALARY
ALTER TABLE DRIVER DROP CONSTRAINT SALARY_CK;
ALTER TABLE DRIVER ADD CONSTRAINT SALARY_CK CHECK(SALARY<70000);

-- RENAMING CONSTRAINT OF LAST NAME COLUMN IN /DRIVER/ TABLE
ALTER TABLE DRIVER RENAME CONSTRAINT LAST_NAME_NN TO NN_LAST_NAME;

-- REANAMING COLUMN NB_OF_ROUND IN /CIRCUIT/ TABLE
ALTER TABLE CIRCUIT RENAME COLUMN NB_OF_ROUND TO NB_OF_ROUNDS;

-- REANAMING COLUMN NB_OF_ROUND IN /COMPETITION/ TABLE
ALTER TABLE COMPETITION RENAME COLUMN NB_OF_ROUND TO NB_OF_ROUNDS;