-- QUESTION 1
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER;

-- QUESTION 2
SELECT LAST_NAME||HIRE_DATE "LAST NAME AND HIRE DATE" FROM DRIVER;

-- QUESTION 3
SELECT LAST_NAME, SALARY * 1.15 FROM DRIVER;

-- QUESTION 4
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE SALARY > 55000;

-- QUESTION 5
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE DRIVER_ID IN ('P300', 'P500', 'P1000');

-- QUESTION 6
SELECT CONSTRUCTOR_ID ,CONSTRUCTOR_NAME FROM CONSTRUCTOR WHERE CONSTRUCTOR_NAME LIKE 'M%';

-- QUESTION 7
SELECT DRIVER_ID, COMP_DATE FROM COMPETITION WHERE QUIT_COMP = 'Y' AND NB_OF_ROUNDS < 60;

-- QUESTION 8
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE LAST_NAME NOT LIKE 'S%';

-- QUESTION 9
SELECT LAST_NAME, FIRST_NAME, TO_CHAR(HIRE_DATE, 'DD-MM-YYYY') FROM DRIVER WHERE HIRE_DATE < TO_DATE('01-01-2000', 'DD-MM-YYYY');

-- QUESTION 10
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE LAST_NAME LIKE '%E%' OR LAST_NAME LIKE '%A%';

-- QUESTION 11
SELECT CONSTRUCTOR_ID FROM COMPETITION GROUP BY CONSTRUCTOR_ID;

-- QUESTION 12
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE SALARY BETWEEN 55000 AND 65000 ORDER BY SALARY ASC;

-- QUESTION 13
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE LAST_NAME LIKE '_A%';

-- QUESTION 14
SELECT CONSTRUCTOR_NAME FROM CONSTRUCTOR WHERE CONSTRUCTOR_NAME LIKE '%O_O%';

-- QUESTION 15
SELECT LAST_NAME, FIRST_NAME, SALARY FROM DRIVER WHERE (LAST_NAME LIKE '%A') OR (LAST_NAME LIKE '%E') OR (LAST_NAME LIKE '%I') OR (LAST_NAME LIKE '%O') OR (LAST_NAME LIKE '%U');

-- QUESTION 16
SELECT DRIVER_ID FROM COMPETITION WHERE NB_OF_ROUNDS IS NULL;