DROP TABLE PERSON;
DROP TABLE CITY;
DROP TABLE COUNTRY;

-- CREATE A TABLE FOR COUNTRY
CREATE TABLE COUNTRY(COUNTRY_ID NUMBER(2) CONSTRAINT PK_COUNTRY_ID PRIMARY KEY,
                     COUNTRY_NAME VARCHAR(30) NOT NULL);
                                    
-- CREATE A TABLE FOR CITIES
CREATE TABLE CITY(CITY_ID NUMBER(2) CONSTRAINT PK_CITY_ID PRIMARY KEY,
                  CITY_NAME VARCHAR(30) CONSTRAINT NN_CITY_NAME NOT NULL,
                  NB_POP NUMBER(4) CONSTRAINT CK_NB_POP CHECK(NB_POP>0),
                  COUNTRY_ID NUMBER(2) CONSTRAINT FK_COUNTRY_ID
                                       REFERENCES COUNTRY(COUNTRY_ID));

-- CREATE A TABLE FOR PERSON
CREATE TABLE PERSON(PERSON_ID NUMBER(6) CONSTRAINT PK_PERSON_ID PRIMARY KEY,
                    PERSON_NAME VARCHAR(30) NOT NULL,
                    PERSON_AGE NUMBER(3) CONSTRAINT CK_PERSON_AGE CHECK(PERSON_AGE>0),
                    PERSON_EMAIL VARCHAR(40) CONSTRAINT UK_PERSON_EMAIL UNIQUE,
                    BIRTH_DATE DATE CONSTRAINT CK_BIRTH_DATE CHECK(birth_date>to_date('10-sep-1900')),
                    CITY_BIRTH NUMBER(2) CONSTRAINT FK_CITY_BIRTH
                                         REFERENCES CITY(CITY_ID),
                    PHONE VARCHAR(30) NOT NULL);
