DROP TABLE REGISTRATION;
DROP TABLE COURSE;
DROP TABLE STUDENT;
DROP TABLE GROUPS;

-- CREATE GROUP TABLE
CREATE TABLE GROUPS(
GROUP_ID NUMBER(2) CONSTRAINT GROUP_ID_PK PRIMARY KEY,
GROUP_DESC VARCHAR(20) CONSTRAINT GROUP_ID_NN NOT NULL,
GROUP_TYPE VARCHAR(30) CONSTRAINT GROUP_ID_CK CHECK(GROUP_TYPE='DEC' OR GROUP_TYPE='AEC' OR GROUP_TYPE='LEA'));

-- CREATE TABLE FOR STUDENT
CREATE TABLE STUDENT(
STUDENT_ID NUMBER(3) CONSTRAINT STUDENT_ID_PK PRIMARY KEY,
LAST_NAME VARCHAR(20) CONSTRAINT LAST_NAME_NN NOT NULL,
FIRST_NAME VARCHAR(20) CONSTRAINT FIRST_NAME_NN NOT NULL,
ADDRESS VARCHAR(30) CONSTRAINT ADDRESS_NN NOT NULL,
BIRTH_DATE DATE,
GROUP_ID NUMBER(2) CONSTRAINT GROUP_ID_FK
                   REFERENCES GROUPS(GROUP_ID));
                   
-- CREATE TABLE FOR COURSE
CREATE TABLE COURSE(
COURSE_ID NUMBER(2) CONSTRAINT COURSE_ID_PK PRIMARY KEY,
COURSE_DESC VARCHAR(20) CONSTRAINT COURSE_DESC_NN NOT NULL,
NMBRE_HOURS NUMBER(2) CONSTRAINT NMBRE_HOURS_CK CHECK(NMBRE_HOURS>=45 AND NMBRE_HOURS<=90));

-- CREATE TABLE FOR REGISTRATION
CREATE TABLE REGISTRATION(
STUDENT_ID NUMBER(3) CONSTRAINT STUDENT_ID_FK2
                     REFERENCES STUDENT(STUDENT_ID),
COURSE_ID NUMBER(2) CONSTRAINT COURSE_ID_FK1
                    REFERENCES COURSE(COURSE_ID),
REGIST_DATE DATE,
CONFIRMATION VARCHAR(3) CONSTRAINT CONFIRMATION_CK CHECK(CONFIRMATION='YES' OR CONFIRMATION='NO'),
                        CONSTRAINT REGISTRATION_PK PRIMARY KEY(STUDENT_ID, COURSE_ID));
                        
-- SELECT CONSTRAINTS FROM TABLE
SELECT CONSTRAINT_NAME,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='GROUPS';
SELECT CONSTRAINT_NAME,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='STUDENT';
SELECT CONSTRAINT_NAME,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='COURSE';
SELECT CONSTRAINT_NAME,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='REGISTRATION';
