CREATE TABLE DEP(
DEP_ID NUMBER(2),
DEP_NAME VARCHAR2(20));

CREATE TABLE EMP(
EMP_ID NUMBER(4) CONSTRAINT EMP_PK PRIMARY KEY,
EMP_NAME VARCHAR2(20));

-- ADDING A COLUMN
ALTER TABLE EMP ADD AGE NUMBER(3) CONSTRAINT EMP_AGE CHECK (AGE>18);

-- ADDING COLUMNS
ALTER TABLE EMP
ADD (PHONE VARCHAR2(30),
     EMAIL VARCHAR2(30) CONSTRAINT EMP_EMP UNIQUE);

-- ADDING A CONSTRAINT TO A COLUMN
ALTER TABLE DEP ADD CONSTRAINT DEP_PK PRIMARY KEY (DEP_ID);

-- ADDING A COLUMN
ALTER TABLE EMP ADD DEP_ID NUMBER(2);

-- ADDING FOREIGN KEY
ALTER TABLE EMP ADD CONSTRAINT FK_EMP_DEP_ID FOREIGN KEY(DEP_ID) REFERENCES DEP(DEP_ID);

-- MODIFYING A COLUMN TYPE
-- *****MUST NOT DROP COLUMN BEFORE MODIFYING******
ALTER TABLE EMP MODIFY EMP_NAME VARCHAR2(30) NOT NULL;

-- MODIFYING A CONSTRAINT
ALTER TABLE EMP DROP CONSTRAINT "CONSTRAINT-NAME";
ALTER TABLE EMP ADD CONSTRAINT "CONSTRAINT-NAME" "TYPE";

-- RENAME A COLUMN
ALTER TABLE EMP RENAME COLUMN AGE TO EMP_AGE;

-- RENAME A CONSTRAINT
ALTER TABLE EMP RENAME CONSTRAINT EMP_EMP TO EMP_EMAIL_UK;

-- DROPPING COLUMN
ALTER TABLE DEP DROP COLUMN DEP_ID CASCADE CONSTRAINTS;

-- DROPPING CONSTRAINT
ALTER TABLE EMP DROP CONSTRAINT EMP_AGE;

