-- DML COMMANDS....CONNECT TO USER BD1*

-- INSERTING A ROW TO ALL COLUMNS IN A TABLE
INSERT INTO DEPT VALUES (10, 'PRODUCTION', 100);
INSERT INTO DEPT VALUES (20, 'ACCOUNTING', 45);
COMMIT; -- MUST ADD THIS COMMAND AFTER ANY COMMAND IN ORDER FOR DATA TO BE VIEWED

INSERT INTO DEPT VALUES (30, 'OPERATIONS', 45);
SELECT * FROM DEPT;
ROLLBACK; -- TAKE OUT OF TEMPORARY STORAGE

-- DATA THAT IS INSERTED ARE STORED IN A TEMPORARY STORAGE UNTIL YOU COMMIT
-- IF YOU WANT TO MOVE SOMETHING FROM TEMPORARY STORAGE TO THE TABLE, YOU MUST COMMIT
-- IF YOU WANT TO REMOVE SOMETHING FROM THE TEMPORARY STORAGE, YOU MUST USE ROLLBACK

-- INSERT DATA TO SPECIFIC COLUMNS IN A TABLE
INSERT INTO EMPL (EMP_ID, EMP_NAME) VALUES (100, 'RICHARD');
INSERT INTO EMPL (EMP_ID, EMP_NAME, EMP_DEP) VALUES (200, 'DAVID', 10);
COMMIT;
SELECT * FROM EMPL;

-- INSERTING DATES DEFAULT ***(YEAR/ MONTH/ DAY)***
SELECT SYSDATE FROM DUAL;
INSERT INTO EMPL (EMP_ID, EMP_NAME, EMP_HDATE) VALUES (400, 'CATHERINE', '2022-04-10');
SELECT * FROM EMPL;
INSERT INTO EMPL (EMP_ID, EMP_NAME, EMP_HDATE) VALUES (500, 'MARIA', TO_DATE('24-10-2022', 'DD-MM-YYYY'));
SELECT * FROM EMPL;
SELECT EMP_ID,TO_CHAR(EMP_HDATE, 'MONTH-DD-YYYY') FROM EMPL;

-- INSERTING DATES WITH SECONDS AND MINUTES
INSERT INTO EMPL (EMP_ID, EMP_NAME, EMP_HDATE) VALUES (600, 'SIMON', TO_DATE('01-JAN-2022 10:05:30', 'DD-MON-YYYY HH24:MI:SS'));
SELECT EMP_ID, EMP_NAME, TO_CHAR(EMP_HDATE, 'DD-MONTH-YYYY HH24:MI:SS') FROM EMPL;

INSERT INTO EMPL (EMP_ID, EMP_NAME, EMP_HDATE) VALUES (700, 'ALI', TO_DATE('28-02-1998 10:10AM', 'DD-MM-YYYY HH:MI AM'));
COMMIT;

SELECT * FROM EMPL;

-- ALTERING THE DEFAULT FORMAT OF THE DATE IF YOU DON'T ALWAYS WANT TO USE THE TO_CHAR FUNCTION
-- ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

-----------------------------------------------------------------------------------------------------------------------------------

-- UPDATING ROWS
UPDATE EMPL SET EMP_AGE=24 WHERE EMP_ID=100;

COMMIT;

-- UPDATE MULTIPLE COLUMNS FOR A ROW
UPDATE EMPL SET EMP_AGE=40, EMP_EMAIL='CATY@GMAIL.COM' WHERE EMP_ID=300;

-- UPDATE DATE FOR A ROW
UPDATE EMPL SET EMP_HDATE=TO_DATE('10-JANUARY-1995', 'DD-MONTH-YYYY') WHERE EMP_ID=100;

COMMIT;

UPDATE EMPL SET EMP_HDATE=TO_DATE('05-MAY-20', 'DD-MON-YY') WHERE EMP_ID=200;
COMMIT;

-------------------------------------------------------------------------------------------------------------------------------------

-- DELETING A ROW
DELETE FROM EMPL WHERE EMP_NAME='ALI';

DELETE FROM EMPL WHERE EMP_HDATE='10-01-2020';

-- DOESN'T WORK
DELETE FROM EMPL WHERE EMP_HDATE='28-02-1998';
-- CORRECTION
DELETE FROM EMPL WHERE TO_CHAR(EMP_HDATE, 'DD-MM-YYY')='28-02-1998';

COMMIT;